FROM python:3.10-slim

RUN apt-get update && apt-get install -y sqlite3 && rm -rf /var/lib/apt/lists/*

RUN useradd -m appuser

WORKDIR /workspace

# -------------------------
# 1. 本番依存
# -------------------------
COPY ../app/scraper/requirements.txt /workspace/app/scraper/requirements.txt
RUN pip install --no-cache-dir -r /workspace/app/scraper/requirements.txt

# -------------------------
# 2. テスト依存
# -------------------------
COPY ../tests/requirements.txt /workspace/tests/requirements.txt
RUN pip install --no-cache-dir -r /workspace/tests/requirements.txt

# -------------------------
# 3. アプリ本体
# -------------------------
COPY ../app /workspace/app
COPY ../tests /workspace/tests

ENV PYTHONPATH=/workspace

# ★ coverage の DB を bind mount の外へ
ENV COVERAGE_FILE=/tmp/.coverage
ENV COVERAGE_HTML_DIR=/tmp/htmlcov


RUN mkdir -p /workspace/tmp

USER appuser

CMD ["pytest"]
