services:
  testpy:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test

    working_dir: /workspace

    environment:
      - COVERAGE_FILE=/tmp/.coverage
      - COVERAGE_HTML_DIR=/tmp/htmlcov

    command: pytest -v --cov=app --cov-report=html --cov-report=term-missing

    volumes:
      - ../app:/workspace/app
      - ../tests:/workspace/tests

    user: "${UID_OVERRIDE}:${GID_OVERRIDE}"
