version: "3.8"

services:
  scraper:
    build: ./docker
    container_name: price-monitor-scraper
    volumes:
      - ./app:/app
      - ./data:/app/data
    environment:
      - TZ=Asia/Tokyo
